# Generated by Django 5.0.3 on 2024-05-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_notification_order_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Fullfilled", "Fullfilled"),
                    ("Cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("disabled", "Disabled"),
                    ("in_review", "In Review"),
                    ("published", "Published"),
                ],
                default="draft",
                max_length=100,
            ),
        ),
    ]
